logging:
  level:
    root: info
    kr.pe.ryudaewan.stiletto: debug
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:stiletto
  http:
    encoding: UTF-8
    enabled: true
    force: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true