server:
  compression:
    enabled: true
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  level:
    root: info
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: error
    kr.pe.ryudaewan.stiletto: debug
spring:
  devtools:
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:stiletto
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true # https://kingbbode.tistory.com/27
  thymeleaf:
    cache: false
